// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6_uyLwpiwqaj8C3SNuFIBVDupnXHzdFc',
    appId: '1:355077050522:web:a1948f2566cd3a1994cf23',
    messagingSenderId: '355077050522',
    projectId: 'zarraga-flood-monitoring',
    authDomain: 'zarraga-flood-monitoring.firebaseapp.com',
    storageBucket: 'zarraga-flood-monitoring.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7xu0Vghq__rMfM_PThGmpGxQsEx2fa2M',
    appId: '1:355077050522:android:54d3a460f3844c1894cf23',
    messagingSenderId: '355077050522',
    projectId: 'zarraga-flood-monitoring',
    storageBucket: 'zarraga-flood-monitoring.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwFYkOmopNv-J_MCXFdTw2GQ6ZcogC9iM',
    appId: '1:355077050522:ios:78d402276a9c6f1294cf23',
    messagingSenderId: '355077050522',
    projectId: 'zarraga-flood-monitoring',
    storageBucket: 'zarraga-flood-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.digitalTwinDataSender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwFYkOmopNv-J_MCXFdTw2GQ6ZcogC9iM',
    appId: '1:355077050522:ios:78d402276a9c6f1294cf23',
    messagingSenderId: '355077050522',
    projectId: 'zarraga-flood-monitoring',
    storageBucket: 'zarraga-flood-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.digitalTwinDataSender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6_uyLwpiwqaj8C3SNuFIBVDupnXHzdFc',
    appId: '1:355077050522:web:84d9f663d980168394cf23',
    messagingSenderId: '355077050522',
    projectId: 'zarraga-flood-monitoring',
    authDomain: 'zarraga-flood-monitoring.firebaseapp.com',
    storageBucket: 'zarraga-flood-monitoring.firebasestorage.app',
  );
}
